### ISSUE TITLE
[Security] An user can send arbitrary HTML code by email

### ISSUE THREAD

**Issue by alexislefebvre** [Victoire/WidgetFormBundle#29]
Because of [this line](https://github.com/Victoire/WidgetFormBundle/blob/550bd2c8a28f1e32e07bc67c8c096919d3d346f1/Resources/views/managerMailTemplate.html.twig#L11), it's possible to send any HTML code and inject malicious code in emails.

The text provided by users should not be trusted, it should not be displayed with the `|raw` filter.

**Comment by alexislefebvre** [comment]
In order to show the line breaks, we can use the CSS rule `white-space: pre;` instead of [`nl2br()`](https://github.com/Victoire/WidgetFormBundle/commit/550bd2c8a28f1e32e07bc67c8c096919d3d346f1#diff-e4b915c81a857ece4e0799d2e344d0b0R45).

**Comment by BFoucher** [comment]
Why we use "raw" filter? it's just for textarea input? we not yet support wysiwyg so i'm think it's not necessary. 
We could use [nl2br](https://twig.sensiolabs.org/doc/2.x/filters/nl2br.html) twig filter no?

**Comment by alexislefebvre** [comment]
@BFoucher In order to display `<br>` as line breaks, we would have to use the `|raw` filter. I prefer the `white-space: pre;` solution that avoid using the `|raw` filter.
